In [1]:
import pandas as pd

df = pd.read_csv('ipl2024-Matches.csv')
df.head()

,id,date,team1,team2,toss_winner,decision,first_score,first_wkts,second_score,second_wkts,winner,player_of_the_match,most_runs,most_wkts
0,1,"March 22,2024",Banglore,Chennai,Banglore,Bat,173,6,176,4,Chennai,Mustafizur Rahman,Anuj Rawat,Mustafizur Rahman
1,2,"March 23,2024",Delhi,Punjab,Punjab,Field,174,9,177,6,Punjab,Sam Curran,Sam Curran,Kuldeep Yadav
2,3,"March 23,2024",Kolkata,Hyderabad,Hyderabad,Field,208,7,204,7,Kolkata,Andre Russell,Andre Russell,T Natarajan
3,4,"March 24,2024",Rajasthan,Lucknow,Rajasthan,Bat,193,4,173,6,Rajasthan,Sanju Samson,Sanju Samson,Trent Boult
4,5,"March 24,2024",Gujarat,Mumbai,Mumbai,Field,168,6,162,9,Gujarat,Sai Sudharsan,Dewald Brevis,Jasprit Bumrah

In [2]:
import pandas as pd

# Load the dataset
df = pd.read_csv("ipl2024-Matches.csv")

# Team wins
print(df['winner'].value_counts())

# Toss impact
print((df['toss_winner'] == df['winner']).sum(), "matches where toss winner also won")

# Player of the Match
print(df['player_of_the_match'].value_counts().head())

# Top performers
print(df['most_runs'].value_counts().head())
print(df['most_wkts'].value_counts().head())

winner
Kolkata      11
Hyderabad     9
Rajasthan     9
Delhi         7
Chennai       7
Banglore      7
Lucknow       7
Punjab        5
Gujarat       5
Mumbai        4
Abandoned     3
Name: count, dtype: int64
31 matches where toss winner also won
player_of_the_match
Sunil Narine       3
Abhishek Sharma    3
Travis Head        3
Sam Curran         2
Ravindra Jadeja    2
Name: count, dtype: int64
most_runs
Virat Kohli        4
Riyan Parag        3
Ruturaj Gaikwad    3
Marcus Stoinis     3
Venkatesh Iyer     3
Name: count, dtype: int64
most_wkts
T Natarajan         3
Jasprit Bumrah      3
Andre Russell       3
Mitchell Starc      3
Tushar Deshpande    2
Name: count, dtype: int64